/// Неправильные глаголы английского: начальная форма → вторая и третья.
///
/// Список частотный, а не полный: детектору конструкций нужно узнавать формы в
/// живом тексте, и хвост из редких глаголов вроде `smite` этого не меняет.
const Map<String, (String, String)> kEnIrregular = {
  'be': ('was', 'been'),
  'become': ('became', 'become'),
  'begin': ('began', 'begun'),
  'break': ('broke', 'broken'),
  'bring': ('brought', 'brought'),
  'build': ('built', 'built'),
  'buy': ('bought', 'bought'),
  'catch': ('caught', 'caught'),
  'choose': ('chose', 'chosen'),
  'come': ('came', 'come'),
  'cost': ('cost', 'cost'),
  'cut': ('cut', 'cut'),
  'do': ('did', 'done'),
  'draw': ('drew', 'drawn'),
  'drink': ('drank', 'drunk'),
  'drive': ('drove', 'driven'),
  'eat': ('ate', 'eaten'),
  'fall': ('fell', 'fallen'),
  'feel': ('felt', 'felt'),
  'find': ('found', 'found'),
  'fly': ('flew', 'flown'),
  'forget': ('forgot', 'forgotten'),
  'get': ('got', 'gotten'),
  'give': ('gave', 'given'),
  'go': ('went', 'gone'),
  'grow': ('grew', 'grown'),
  'have': ('had', 'had'),
  'hear': ('heard', 'heard'),
  'hold': ('held', 'held'),
  'keep': ('kept', 'kept'),
  'know': ('knew', 'known'),
  'leave': ('left', 'left'),
  'lose': ('lost', 'lost'),
  'make': ('made', 'made'),
  'mean': ('meant', 'meant'),
  'meet': ('met', 'met'),
  'pay': ('paid', 'paid'),
  'put': ('put', 'put'),
  'read': ('read', 'read'),
  'ride': ('rode', 'ridden'),
  'run': ('ran', 'run'),
  'say': ('said', 'said'),
  'see': ('saw', 'seen'),
  'sell': ('sold', 'sold'),
  'send': ('sent', 'sent'),
  'set': ('set', 'set'),
  'show': ('showed', 'shown'),
  'sing': ('sang', 'sung'),
  'sit': ('sat', 'sat'),
  'sleep': ('slept', 'slept'),
  'speak': ('spoke', 'spoken'),
  'spend': ('spent', 'spent'),
  'stand': ('stood', 'stood'),
  'steal': ('stole', 'stolen'),
  'take': ('took', 'taken'),
  'teach': ('taught', 'taught'),
  'tell': ('told', 'told'),
  'think': ('thought', 'thought'),
  'throw': ('threw', 'thrown'),
  'understand': ('understood', 'understood'),
  'wear': ('wore', 'worn'),
  'win': ('won', 'won'),
  'write': ('wrote', 'written'),
};

